### PR TITLE
Add --shuffle to shuffle tracks

### PR DESCRIPTION
**Pull request by Sixeight**
bgm.rb always plays tracks in same order. We got bored :dancers:

I propose a `--shuffle` option to shuffle tracks.
Now, we can get a nice music in random order.

```
$ bundle exec -- ruby bgm.rb "Crystal Castel" --shuffle
```

### CODE REVIEW

**Comment by hitode909** [comment]
LGTM

Could you write some documentation at README.md?

**Comment by Sixeight** [comment]
Oh, I'm sorry. I'll write documentation as soon as possible.

**Comment by Sixeight** [comment]
Done :white_check_mark:

**Comment by hitode909** [comment]
LGTM!!!

LGTM

**Pull request merged**
